# Use an official Node.js runtime as a parent image
FROM node:14 AS build

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Copy .env file
COPY .env .env

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Use an official NGINX image to serve the app
FROM nginx:alpine

# Copy the build output to the NGINX html directory
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Expose the port NGINX runs on
EXPOSE 80

# Command to run NGINX
CMD ["nginx", "-g", "daemon off;"]
