name: Bitcoin Explorer App
services:
- name: backend
  image:
    registry: aditi20000/backend
    tag: latest
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    value: postgres://user:bit@db:5432/bitcoin_explorer
  ports:
  - port: 4000
    protocol: HTTP

- name: frontend
  image:
    registry: aditi20000/frontend
    tag: latest
  envs:
  - key: NODE_ENV
    value: production
  ports:
  - port: 80
    protocol: HTTP

- name: bitcoin_ingestion
  image:
    registry: aditi20000/bitcoin_ingestion
    tag: latest
  envs:
  - key: DATABASE_URL
    value: postgres://user:bit@db:5432/bitcoin_explorer

databases:
- name: db
  engine: pg
  version: "14"
  size: db-s-1vcpu-1gb
  num_nodes: 1
  user: user
  password: bit
  dbname: bitcoin_explorer
