version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
      - bitcoin_core

  frontend:
    build:
      context: ./bitcoin-explorer
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  bitcoin_ingestion:
    build:
      context: ./bitcoin_ingestion
    depends_on:
      - db
      - bitcoin_core
    entrypoint: ./wait-for-it.sh db:5432 -- ./target/release/bitcoin_ingestion

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: bit
      POSTGRES_DB: bitcoin_explorer
    volumes:
      - pgdata:/var/lib/postgresql/data

  bitcoin_core:
    image: ruimarinho/bitcoin-core:latest
    ports:
      - "8332:8332"
      - "8333:8333"
    volumes:
      - bitcoin_data:/bitcoin
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_RPCUSER: user
      BITCOIN_RPCPASSWORD: password

volumes:
  pgdata:
  bitcoin_data:
