version: '3'
 
services:

  db:

    image: postgres:13

    environment:

      POSTGRES_USER: bit

      POSTGRES_PASSWORD: bit

      POSTGRES_DB: bitcoin_explorer

    ports:

      - "5432:5432"

    volumes:

      - db_data:/var/lib/postgresql/data
 
  backend:

    build: ./backend

    depends_on:

      - db

    environment:

      - PGUSER=bit

      - PGPASSWORD=bit

      - PGDATABASE=bitcoin_explorer

      - PGHOST=db

      - PGPORT=5432

    ports:

      - "4000:4000"

    command: ["node", "index.js"]
 
  frontend:

    build: ./bitcoin-explorer

    ports:

      - "80:80"

    depends_on:

      - backend
 
  rust_ingestion:

    build:

      context: ./bitcoin_ingestion

      dockerfile: Dockerfile

    depends_on:

      - db

    environment:

      - PGUSER=bit

      - PGPASSWORD=bit

      - PGDATABASE=bitcoin_explorer

      - PGHOST=db

      - PGPORT=5432
 
volumes:

  db_data:
