# Use the official Rust image as a parent image
FROM rust:latest
 
# Set the working directory
WORKDIR /usr/src/app
 
# Copy the Cargo.toml and Cargo.lock files
COPY Cargo.toml Cargo.lock ./
 
# Copy the source code
COPY src ./src
 
# Build the application
RUN cargo build --release
 
# Run the application
CMD ["cargo", "run", "--release"]