name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t ${{ secrets.DOCKER_REPO }}:backend ./backend
        docker build -t ${{ secrets.DOCKER_REPO }}:frontend ./bitcoin-explorer
        docker build -t ${{ secrets.DOCKER_REPO }}:ingestion ./bitcoin_ingestion
        docker push ${{ secrets.DOCKER_REPO }}:backend
        docker push ${{ secrets.DOCKER_REPO }}:frontend
        docker push ${{ secrets.DOCKER_REPO }}:ingestion

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Install Docker
          apt-get update
          apt-get install -y docker.io
          systemctl start docker
          systemctl enable docker

          # Install Docker Compose
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

          # Ensure deployment directory exists
          mkdir -p /root/deployment

    - name: Copy project files to Droplet
      uses: appleboy/scp-action@v0.1.0
      with:
        source: './*'
        target: '/root/deployment/'
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        strip_components: 1

    - name: Run Docker Compose
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /root/deployment
          docker pull ${{ secrets.DOCKER_REPO }}:backend
          docker pull ${{ secrets.DOCKER_REPO }}:frontend
          docker pull ${{ secrets.DOCKER_REPO }}:ingestion
          docker-compose up -d
