name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./bitcoin-explorer
          file: ./bitcoin-explorer/dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/bitcoin-explorer-frontend:latest

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/bitcoin-explorer-backend:latest

      - name: Build and push ingestion Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./bitcoin_ingestion
          file: ./bitcoin_ingestion/dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/bitcoin-ingestion:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} "
            cd /root/info7500-crypto &&
            docker-compose pull &&
            docker-compose up -d
          "
