name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
        docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./bitcoin-explorer
        docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/bitcoin_ingestion:latest ./bitcoin_ingestion

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install doctl
      run: |
        curl -sL https://github.com/digitalocean/doctl/releases/download/v1.64.0/doctl-1.64.0-linux-amd64.tar.gz | tar -xzv
        sudo mv doctl /usr/local/bin

    - name: Authenticate with DigitalOcean
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: doctl auth init -t $DIGITALOCEAN_ACCESS_TOKEN

    - name: Deploy to DigitalOcean
      run: |
        doctl apps create --spec app-spec.yml
